In [7]:
import re
import pandas as pd

In [8]:
def date_time(s):
    pattern = '^([0-9]+)(\/)([0-9]+)(\/)([0-9]+), ([0-9]+):([0-9]+)[ ]?(AM|PM|am|pm)? -'
    result = re.match(pattern, s)
    if result:
        return True
    else:
        pattern = '\d{1,2}/\d{1,2}/\d{2,4},\s\d{1,2}:\d{2}\s-\s'
        result = re.match(pattern, s)
        if result:
            return True
        else:
            return False

In [9]:
def getDatapoint(line):
    splitline = line.split(' - ')
    dateTime = splitline[0]
    date, time = dateTime.split(", ")
    message = " ".join(splitline[1:])
    splitmessage = message.split(": ")
    if splitmessage[1:]:
        author = splitmessage[0]
        message = " ".join(splitmessage[1:])
    else:
        author = 'group_notification'
        message = splitmessage[0]
    return date, time, author, message

In [10]:
data = []
conversation = 'aa.txt'
fp=open('WhatsApp Chat with TY-MP T3-11.txt','r',encoding='utf-8');
fp.readline()
messageBuffer = []
date, time, user = None, None, None
while True:
    line = fp.readline()
    if not line:
        break
    line = line.strip()
    if date_time(line):
        if len(messageBuffer) > 0:
            data.append([date, time, user, ' '.join(messageBuffer)])
        messageBuffer.clear()
        date, time, user, message = getDatapoint(line)
        messageBuffer.append(message)
    else:
        messageBuffer.append(line)

In [11]:
df = pd.DataFrame(data, columns=["date", 'time', 'user', 'message'])
df['date'] = pd.to_datetime(df['date'])
df['time'] = pd.to_datetime(df['time'])
df.head()

,date,time,user,message
0,2021-08-08,2022-04-21 11:58:00,group_notification,"Teknath Jha created group ""Ty-mini Project"""
1,2021-08-08,2022-04-21 11:58:00,group_notification,Teknath Jha added you
2,2021-08-08,2022-04-21 11:59:00,Teknath Jha,aapne aapne skills batao (languages you know...
3,2021-08-08,2022-04-21 12:01:00,Sanap Aditya,"React ,HTML,CSS ,JS ,Python basics"
4,2021-08-08,2022-04-21 13:19:00,Avinash,"Coordinates iot, ai,ml modern ka karneki bolte..."

In [12]:
df['only_date'] = df['date'].dt.date
df['year'] = df['date'].dt.year
df['month_num'] = df['date'].dt.month
df['month'] = df['date'].dt.month_name()
df['day'] = df['date'].dt.day
df['day_name'] = df['date'].dt.day_name()
df['hour'] = df['time'].dt.hour
df['minute'] = df['time'].dt.minute

In [59]:
df.head(20)

,date,time,user,message,only_date,year,month_num,month,day,day_name,hour,minute
0,2021-08-08,2022-04-21 11:58:00,group_notification,"Teknath Jha created group ""Ty-mini Project""",2021-08-08,2021,8,August,8,Sunday,11,58
1,2021-08-08,2022-04-21 11:58:00,group_notification,Teknath Jha added you,2021-08-08,2021,8,August,8,Sunday,11,58
2,2021-08-08,2022-04-21 11:59:00,Teknath Jha,aapne aapne skills batao (languages you know...,2021-08-08,2021,8,August,8,Sunday,11,59
3,2021-08-08,2022-04-21 12:01:00,Sanap Aditya,"React ,HTML,CSS ,JS ,Python basics",2021-08-08,2021,8,August,8,Sunday,12,1
4,2021-08-08,2022-04-21 13:19:00,Avinash,"Coordinates iot, ai,ml modern ka karneki bolte...",2021-08-08,2021,8,August,8,Sunday,13,19
5,2021-08-08,2022-04-21 13:20:00,Avinash,Abhi itna tension mat lo batate ho konsa techn...,2021-08-08,2021,8,August,8,Sunday,13,20
6,2021-08-08,2022-04-21 16:11:00,Avinash,You deleted this message,2021-08-08,2021,8,August,8,Sunday,16,11
7,2021-08-08,2022-04-21 16:12:00,Avinash,Form bhardo koi to,2021-08-08,2021,8,August,8,Sunday,16,12
8,2021-08-08,2022-04-21 16:12:00,Sanap Aditya,Bol ith mail taka,2021-08-08,2021,8,August,8,Sunday,16,12
9,2021-08-08,2022-04-21 16:12:00,Sanap Aditya,mi bharto,2021-08-08,2021,8,August,8,Sunday,16,12
10,2021-08-08,2022-04-21 16:12:00,Avinash,Koni tari ekanech bharychay,2021-08-08,2021,8,August,8,Sunday,16,12
11,2021-08-08,2022-04-21 16:13:00,Sanap Aditya,ha,2021-08-08,2021,8,August,8,Sunday,16,13
12,2021-08-08,2022-04-21 16:13:00,Avinash,Bhato ka mag,2021-08-08,2021,8,August,8,Sunday,16,13
13,2021-08-08,2022-04-21 16:13:00,Sanap Aditya,ha mail dalo idhAR,2021-08-08,2021,8,August,8,Sunday,16,13
14,2021-08-08,2022-04-21 16:14:00,Avinash,avinash.biradar@walchandsangli.ac.in,2021-08-08,2021,8,August,8,Sunday,16,14
15,2021-08-08,2022-04-21 16:14:00,Sanap Aditya,prn pn taka,2021-08-08,2021,8,August,8,Sunday,16,14
16,2021-08-08,2022-04-21 16:14:00,Avinash,Teknath.jha@walchandsangli.ac.in prn 33,2021-08-08,2021,8,August,8,Sunday,16,14
17,2021-08-08,2022-04-21 16:14:00,Avinash,77,2021-08-08,2021,8,August,8,Sunday,16,14
18,2021-08-08,2022-04-21 16:14:00,Sanap Aditya,T capital a ka,2021-08-08,2021,8,August,8,Sunday,16,14
19,2021-08-08,2022-04-21 16:15:00,Avinash,Sry small ahe,2021-08-08,2021,8,August,8,Sunday,16,15